#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login

new_register:
    path: /api/register

posts:
    path: /api/post

lists:
    resource  : App\Controller\PostController
    prefix    : api